#!/bin/bash
if [[ $# -lt 1 ]]; then
	echo usage: $0 output.mp4 input1.mp4 input2.mp4 [...]
	exit 1
fi

for i in ${@:2}; do echo "file '$i'"; done >$1.list
ffmpeg -f concat -i $1.list -c copy $1
rm $1.list
