#!/bin/bash

REMOTE=/net/seagoat/c3

[[ `find ~/bin/sync_seagoat.last -mmin -720 | wc -l` -gt 0 ]] && exit 0

mountpoint -q $REMOTE || exit 0
ls $REMOTE &>/dev/null || exit 0

TODAY=$(date +%Y%m%d)

(
# windows jatekallasok
if mountpoint -q /mnt/win10; then
	# na ez egy furi dolog. $HOME/Saved Games tokures, viszont van jatekallas mindenhol szanaszejjel.
	tar cjf $REMOTE/backup/bruin/win-$TODAY.tar.bz2 \
	--exclude='/mnt/win10/Users/gazember/AppData/Roaming/.minecraft*' \
	'/mnt/win10/Users/gazember/AppData/Roaming' \
	'/mnt/win8/Program Files (x86)/Steam/userdata' \
	'/mnt/win10/Program Files (x86)/Steam/userdata' \
	/mnt/win10/Users/gazember/cc_save.dat*
fi
# ezt peti telefosta memekkel
#	'/mnt/win10/Users/gazember/Documents' \



# pepperflash storage - peti flash jatekallasok
#tar cjf /net/seagoat/home/ftp/backup/bruin/pepperflash-${TODAY}.tar.bz2 '/home/us/.config/google-chrome/Default/Pepper Data/'

# home
rsync -avH --delete --ignore-errors /home/us/ $REMOTE/backup/bruin/home/us/

# webplay
#rsync -avH --delete --ignore-errors $REMOTE/www/webplay/ /var/www/webplay/

# backup seagoat
if mountpoint -q /mnt/backup.crypted; then
	cat ~/.encfs | encfs /mnt/backup.crypted /mnt/backup -i 5 -S
	rsync -avH --delete --ignore-errors $REMOTE/{archive,book,apps,everyday_life,games,music,www} /mnt/backup/
	rsync -avH --delete --ignore-errors $REMOTE/backup/seagoat /mnt/backup/backup/
	fusermount -uz /mnt/backup
fi

# we don't run again within 24 hours
touch ~/bin/sync_seagoat.last

) &>~/bin/sync_seagoat.out
