#!/bin/bash

[[ `find ~/bin/sync_seagoat.last -mmin -720 | wc -l` -gt 0 ]] && exit 0

# quit if src/dst doesn't exist
mountpoint /net/seagoat/home/ftp || exit 0

TODAY=$(date +%Y%m%d)

(

# windows jatekallasok
if mountpoint /mnt/win10; then
	# na ez egy furi dolog. $HOME/Saved Games tokures, viszont van jatekallas mindenhol szanaszejjel.
	tar cjf /net/seagoat/home/ftp/backup/bruin/win-$TODAY.tar.bz2 \
	'/mnt/win10/Users/gazember/AppData/Roaming' \
	'/mnt/win8/Program Files (x86)/Steam/userdata' \
	'/mnt/win10/Program Files (x86)/Steam/userdata' \
	'/mnt/win10/Users/gazember/Documents' \
	'/mnt/win10/Users/gazember/cc_save.dat'
fi

# pepperflash storage - peti flash jatekallasok
tar cjf /net/seagoat/home/ftp/backup/bruin/pepperflash-${TODAY}.tar.bz2 '/home/us/.config/google-chrome/Default/Pepper Data/'

# home
rsync -avH --delete --ignore-errors /home/us/ /net/seagoat/home/ftp/backup/bruin/home/us/

# webplay
rsync -avH --delete --ignore-errors /net/seagoat/home/ftp/www/webplay/ /var/www/webplay/

# backup seagoat
if mountpoint /mnt/backup.crypted; then
	cat ~/.encfs | encfs /mnt/backup.crypted /mnt/backup -i 5 -S
	rsync -avH --delete --ignore-errors /net/seagoat/home/ftp/{archive,book,apps,everyday_life,games,music,www} /mnt/backup/
	rsync -avH --delete --ignore-errors /net/seagoat/home/ftp/backup/{cica,maci,seagoat,webplay} /mnt/backup/backup/
	fusermount -uz /mnt/backup
fi

# we don't run again within 24 hours
touch ~/bin/sync_seagoat.last

) &>~/bin/sync_seagoat.out
