#!/bin/bash
if [ $# -lt 1 ]; then
	echo 'Hasznalat: keres <kifejezes>'
	exit 1
fi

FILE=`tempfile`

cd ~/ibi/Forditas
for i in *.doc; do
	catdoc -w "$i" | grep --color=always -i "$*" >$FILE
	if [ -s $FILE ]; then
		TERM=linux setterm -foreground green -bold on
		echo " >>> $i"
		TERM=linux setterm -foreground default -bold off
		cat $FILE
	fi
done

rm -f $FILE
